#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "$REPO_ROOT"

MODEL_NAME_OR_PATH="Qwen/Qwen2.5-3B-Instruct"
TRAIN_JSONL="./data/train.jsonl"
EVAL_SPLIT_RATIO="0.05"
EVAL_SPLIT_SEED="42"
NUM_GPUS="4"
ZERO_STAGE="3"
DEEPSPEED_CONFIG_PATH="src/deepspeed_zero${ZERO_STAGE}.json"
WANDB_PROJECT="drift"
RUN_NAME="qwen2.5-3b-weighted-sft"
REPORT_TO="none"
OUTPUT_DIR="./outputs/weighted-sft/${RUN_NAME}"

MAX_COMPLETION_LENGTH="512"
MAX_PROMPT_LENGTH="8192"
PER_DEVICE_TRAIN_BATCH_SIZE="2"
PER_DEVICE_EVAL_BATCH_SIZE="4"
GRAD_ACCUM_STEPS="16"
LEARNING_RATE="5e-6"
LR_SCHEDULER_TYPE="constant_with_warmup"
NUM_TRAIN_EPOCHS="1"
WARMUP_RATIO="0.1"
GAMMA="0.9"
BETA="0.1"
LOGGING_STEPS="1"
EVAL_STEPS="20"
SAVE_STEPS="200"
SAVE_TOTAL_LIMIT="3"
WEIGHT_DECAY="0.1"
MAX_GRAD_NORM="1.0"
TRUNCATION_SIDE="left"
SEED="42"

export WANDB_PROJECT="$WANDB_PROJECT"
export WANDB_NAME="$RUN_NAME"
export BATCH_WEIGHT_NORMAL="False"

cmd=(
  deepspeed
  --num_gpus "$NUM_GPUS"
  src/weight_sft.py
  --model_name_or_path "$MODEL_NAME_OR_PATH"
  --train_jsonl "$TRAIN_JSONL"
  --output_dir "$OUTPUT_DIR"
  --max_prompt_length "$MAX_PROMPT_LENGTH"
  --max_completion_length "$MAX_COMPLETION_LENGTH"
  --per_device_train_batch_size "$PER_DEVICE_TRAIN_BATCH_SIZE"
  --gradient_accumulation_steps "$GRAD_ACCUM_STEPS"
  --learning_rate "$LEARNING_RATE"
  --lr_scheduler_type "$LR_SCHEDULER_TYPE"
  --num_train_epochs "$NUM_TRAIN_EPOCHS"
  --warmup_ratio "$WARMUP_RATIO"
  --gamma "$GAMMA"
  --beta "$BETA"
  --logging_steps "$LOGGING_STEPS"
  --save_steps "$SAVE_STEPS"
  --save_total_limit "$SAVE_TOTAL_LIMIT"
  --weight_decay "$WEIGHT_DECAY"
  --max_grad_norm "$MAX_GRAD_NORM"
  --truncation_side "$TRUNCATION_SIDE"
  --seed "$SEED"
  --zero_stage "$ZERO_STAGE"
  --report_to "$REPORT_TO"
  --eval_split_ratio "$EVAL_SPLIT_RATIO"
  --eval_split_seed "$EVAL_SPLIT_SEED"
  --eval_steps "$EVAL_STEPS"
  --run_name "$RUN_NAME"
  --per_device_eval_batch_size "$PER_DEVICE_EVAL_BATCH_SIZE"
  --deepspeed_config_path "$DEEPSPEED_CONFIG_PATH"
  --bf16
  --disable_shuffle
)

exec "${cmd[@]}"
